#!/bin/sh
# Copyright (c) 2001 Sun Microsystems, Inc.
# All Rights Reserved.
# 
# See the file "license.terms" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL 
# WARRANTIES.
#
sh compareUtt Unit 
sh compareUtt target_end 
sh compareNumericUtt f0 
sh compareUtt accent 
sh compareUtt stress
sh compareUtt Segment
sh compareUtt SylStructure
sh compareUtt Word
sh compareUtt Phrase
sh compareUtt Token
sh compareUtt pos
sh compareUtt endtone

# The file_pos test has been removed. A refactoring
# of the tokenization process now causes freetts to
# give file_pos values that are relative to the FreeTTSSpeakable
# not just to the utterance. This is much preferred as compared to
# the previous file_pos within an utterance. So even thought the
# output of freetts does not match flite with regard to the file_pos
# we like our answer better.
#
# compareUtt file_pos
